// <auto-generated />
using BerrasBio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BerrasBio.Migrations
{
    [DbContext(typeof(BerraContext))]
    partial class BerraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BerrasBio.Models.Entity.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NumOfSeats");

                    b.Property<int>("ShowingID");

                    b.HasKey("ID");

                    b.HasIndex("ShowingID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BerrasBio.Models.Entity.Movie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.Property<int>("RunningMinutes");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("BerrasBio.Models.Entity.Salon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MaxSeats");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("BerrasBio.Models.Entity.Showing", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("MovieID");

                    b.Property<int>("SalonID");

                    b.HasKey("ID");

                    b.HasIndex("MovieID");

                    b.HasIndex("SalonID");

                    b.ToTable("Showings");
                });

            modelBuilder.Entity("BerrasBio.Models.Entity.Booking", b =>
                {
                    b.HasOne("BerrasBio.Models.Entity.Showing", "Showing")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BerrasBio.Models.Entity.Showing", b =>
                {
                    b.HasOne("BerrasBio.Models.Entity.Movie", "Movie")
                        .WithMany("Showings")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BerrasBio.Models.Entity.Salon", "Salon")
                        .WithMany("Showings")
                        .HasForeignKey("SalonID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
